spring:
  datasource:
    # Saves a file named portfoliodb.mv.db in a 'data' folder in your project root
    url: jdbc:h2:file:./data/portfoliodb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

cloudinary:
  application:
    name: dev-portfolio