spring:
  application:
    name: portfolio-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: caffeine
    cache-names:
      - cloud-file-urls
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=8m
    max: 1000
    ttl: 8 #8min

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  privateUrlTtl: 10m # 10min

springdoc:
  swagger-ui:
    path: /api/docs
  api-docs:
    path: /api/openapi